server:
  port: 8763

spring:
  zipkin:
    base-url: http://192.168.3.42:9411

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.41:3306/sys-blog?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: 192.168.3.41
    port: 5672
    username: test
    password: test
    publisher-confirms: true
    virtual-host: /