hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    schoolwebservice:
      path: /aosschoolapi/**
      serviceId: schoolwebservice
      sensitiveHeaders:
    user-service-gov:
      path: /aosuserapi/**
      serviceId: user-service-gov
      sensitiveHeaders:

server:
  port: 5000

