hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    uaa-service:
      path: /uaaapi/**
      serviceId: uaa-service
      sensitiveHeaders:
    user-service:
      path: /userapi/**
      serviceId: user-service
      sensitiveHeaders:

    blog-service:
      path: /blogapi/**
      serviceId: blog-service
      sensitiveHeaders:
    user-service-gov:
      path: /aoxuserapi/**
      serviceId: user-service-gov
      sensitiveHeaders:

server:
  port: 5000

